### ISSUE TITLE
Отсутствует файл проекта .project

### ISSUE THREAD

**Issue by 678098** [einerfreiheit/life_simulation#2]
Надо его добавить.
Алгоритм таков:
1)Получить свежую версию ветки master:
git checkout master
git pull origin master
2)Создать новую ветку 170218_added_missing_project_file:
git checkout -b 170218_added_missing_project_file
3)Добавить недостающий файл:
git add .project
(команду выполнять из верхней папки репозитория)
4)Проверить, что файл включен в коммит:
git status
Файл .project должен отобразиться в консоли зелёным
5)Сделать коммит:
git commit -m "добавлен недостающий файл .project"
6)Отправить изменения в ветке на сервер:
git push origin 170218_added_missing_project_file
7)Сделать pull-request на сервере.
Для этого надо в браузере в репозитории найти пулл-реквесты и создать новый, в качестве двух веток для слияния надо указать master и 170218_added_missing_project_file

**Comment by einerfreiheit** [comment]
Можно закрывать?
