### ISSUE TITLE
Придумать годные ресурсы для клеток и добавить их

### ISSUE THREAD

**Issue by 678098** [einerfreiheit/life_simulation#26]
Можно придумать возобновляемые и невозобновляемые.
От этого шага и логичности ресов будет сильно зависеть всё последующее.

**Comment by einerfreiheit** [comment]
С другой стороны, надо определиться с червями: могут ли они производить ресурсы; в теории можно сделать замкнутую систему, где все ресурсы будут перерабатываться.
Тут просто очень много вариантов
