### ISSUE TITLE
Добавить в README.md инструкции по установке и сборке (включая установку требуемых библиотек)

### ISSUE THREAD

**Issue by 678098** [einerfreiheit/life_simulation#56]

**Comment by latticetower** [comment]
Неплохо также добавить минимальное количество тестов или, в качестве smoke-теста - конфиг для Travis-CI с типичным вариантом сборки и запуска - чтобы понимать, что приложение хотя бы собирается при заданных параметрах сборки и не завершается ошибкой при запуске.
Про Travis-CI можно начать читать, например, отсюда: https://docs.travis-ci.com/user/for-beginners

**Comment by latticetower** [comment]
Еще можно прикрутить какую-то систему сборки проектов или хотя бы Makefile добавить.

**Comment by 678098** [comment]
Там есть CMakeLists.txt, если ты не заметила.
И писать тесты, пока чел не знает ещё на зубок основ крестов - это интересная затея.
Давай задачи пореальнее.

**Comment by latticetower** [comment]
@678098 под smoke-тестом я подразумеваю примерно вот что: просто написать для Travis-CI конфиг, который будет вызывать скрипт для сборки приложения и запускать то, что собирается, с каким-то параметром (или без). На текущем этапе я не предлагаю писать тесты непосредственно к плюсовому коду.
А про CMakeLists.txt - проглядела)

**Comment by 678098** [comment]
Надо поправить переводы строк в readme.

**Comment by einerfreiheit** [comment]
а так инструкция потянет?
